schema_version = "1.0.0"

id = "maya_viewport_match"
version = "0.22.8"
name = "QC Maya Viewport"
tagline = "QC Maya Viewport diagnostic GPU shading for Blender"
maintainer = "Mutaform Studio"
type = "add-on"

blender_version_min = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
